### ISSUE TITLE
While-Loop-Closure-Asymmetry in readme

### ISSUE THREAD

**Issue by AntonioNoack** [dvtate/dlang20#1]
Hello Dustin,

I haven't downloaded and run your language yet, however in your example for the while loop in the readme,
`
let n = 0;
while ((: n < 5 ), (: 
    n += 1;
    print(n);
);
`
contains one opening bracket (5) more than closing brackets (4).
Probably it's just a typo, but it might be your intended syntax ;).

If it's intended syntax, it would bother me personally; probably because I am not used to it xD.

**Comment by dvtate** [comment]
Yes that's a typo, thanks!

Also if you don't mind, what's your opinion on using curlies `{}` for closures instead of `(: )`?

![image](https://user-images.githubusercontent.com/15305612/86834374-627d6580-c060-11ea-95c3-81b231233682.png)

**Comment by dvtate** [comment]
I should also probably keep an up to date list of example/test programs because some of the programs in the README have features that aren't ready yet (and require workarounds)

**Comment by AntonioNoack** [comment]
I personally like {} better, because I am familiar with them (in Kotlin and JavaScript).
Also I feel like they make the code a bit easier to read, because there is better distinction of closing brackets (which bracket belongs to which block of code) :). Me being used to C-Syntax, I definitively wouldn't use [], because they belong to arrays ;).
